### ISSUE TITLE
problem using path

### ISSUE THREAD

**Issue by vrfox** [VeliovGroup/ostrio-neo4jdriver#43]
```js
  neo4j.query('unwind [' + usersArr + '] as ids match p=(n{_id: ids})<-[rel*0..]-(u{username: "admin"}) return ([x in nodes(p) | x._id]) as array').fetch();
```

``` 
I20170424-22:41:35.092(-6)? java.util.ArrayList cannot be cast to java.util.Map
W20170424-22:41:35.097(-6)? (STDERR)
W20170424-22:41:35.098(-6)? (STDERR) C:\Users\fox\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:278
W20170424-22:41:35.098(-6)? (STDERR)                                            throw(ex);
W20170424-22:41:35.098(-6)? (STDERR)                                                  ^
W20170424-22:41:35.098(-6)? (STDERR) ReferenceError: __error is not defined
W20170424-22:41:35.099(-6)? (STDERR)     at Neo4jNode.<anonymous> (C:\Users\fox\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2\npm\node_modules\neo4j-fiber\lib\node.js:70:22)
W20170424-22:41:35.099(-6)? (STDERR)     at Neo4jNode.emit (events.js:95:17)
W20170424-22:41:35.099(-6)? (STDERR)     at new Neo4jNode (C:\Users\fox\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2\npm\node_modules\neo4j-fiber\lib\node.js:83:16)
W20170424-22:41:35.099(-6)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__parseRow (C:\Users\fox\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2\npm\node_modules\neo4j-fiber\lib\driver.js:410:32)
W20170424-22:41:35.100(-6)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__parseResponse (C:\Users\fox\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2\npm\node_modules\neo4j-fiber\lib\driver.js:428:23)
W20170424-22:41:35.100(-6)? (STDERR)     at Neo4jDB.module.exports.Neo4jDB.__transformData (C:\Users\fox\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2\npm\node_modules\neo4j-fiber\lib\driver.js:442:43)
W20170424-22:41:35.100(-6)? (STDERR)     at C:\Users\fox\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2\npm\node_modules\neo4j-fiber\lib\driver.js:219:69
W20170424-22:41:35.101(-6)? (STDERR)     at C:\Users\fox\AppData\Local\.meteor\packages\ostrio_neo4jdriver\1.0.2\npm\node_modules\neo4j-fiber\lib\helpers.js:44:16
```

any ideas on this one
v1.0.2 and neo4j 2.3.10

**Comment by dr-dimitru** [comment]
Hello @vr-fox 

Sorry for late reply.
Looks like you bump into [#6](https://github.com/VeliovGroup/neo4j-fiber/issues/6), which was fixed in [v1.0.3](https://github.com/VeliovGroup/neo4j-fiber/releases/tag/1.0.3)

Any chance you can upgrade to latest release?
Let me know if it helps you.

**Comment by dr-dimitru** [comment]
Hello @vr-fox ,

Any news on your end?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
